### PR TITLE
Add Stripe as a default payment gateway, update to Next 9.5

### PR DESCRIPTION
**Pull request by robbieaverill**
- Add built in support for Stripe as a payment gateway
- Update Next to 9.5.x

We have another issue at #139 to update to Next 10. I updated to 9.5 so we can use the new environment variable handling that was added in 9.4.

Also adds the shipping cost to the checkout receipt.

### CODE REVIEW

**Review by ScopeyNZ — COMMENTED** [review]
LGTM. Couple of questions:

- Are we okay using a canary version of Next?
- Is there any oppurtunity to break up the CheckoutPage? It's getting pretty massive for an `index.js` file...

**Comment by robbieaverill** [comment]
> Are we okay using a canary version of Next?

We want to move to Next 10 in #139 anyway, so I figured that the release I've pinned to is likely to be the least buggy of the 9.5.x release line. If we're concerned I can pin back to the latest stable patch version though.

> Is there any oppurtunity to break up the CheckoutPage? It's getting pretty massive for an index.js file...

Yep, but nothing is scheduled. There's a lot of opportunity to tidy up the code in this repository.

**Comment by robbieaverill** [comment]
I've rebased and pinned Next back to 9.5.5

**Review by ScopeyNZ — APPROVED** [review]

**Comment by ScopeyNZ** [comment]
One moment, just checking one more thing.

**Pull request merged**
