### PR TITLE
Bugfix/Hydrated categories and products

### LINKED ISSUE #59: Bug/Store data not persisting going from one getStaticProps product display page to another
Store data like items in cart not persisted going from one `getStaticProps` "product detail page" to another after `next-wrapper-redux` udpate

### PR DESCRIPTION
**Pull request by jaepass**
Closes #59 
- Fixed client data like items in cart not being persisted going from `getStaticProps` product detail page to another

### CODE REVIEW

**Comment by jaepass** [comment]
Thank you Robbie

**Comment by jaepass** [comment]
niice, this fixed merging client cart and ssr categories and products properly. im still unsure why adding second product item still triggers `ADD_TO_CART_ERROR` since when it hydrates the second time, states are equal

**Comment by robbieaverill** [comment]
I'm looking at that now - is that #47 you're talking about?

**Comment by jaepass** [comment]
yes #47 should i just condense down to one issue since they're related

**Comment by robbieaverill** [comment]
No I don't think so. This PR fixes #59 so let's merge and leave 47 open

**Pull request merged**
