### PR TITLE
[CHEC-709] Add to cart animation & checkout loader

### PR DESCRIPTION
**Pull request by jaepass**
- Package updated to include react-lottie
- Added lottie files for add to cart animation and order capture animation
- Created components for both animations
- Rendered add to cart animation in the header component
- Rendered order capture animation in the checkout view
- Added some alt attribute to get rid of errors

** @john-raymon was a big help on implementing the add to cart animation**

### CODE REVIEW

**Comment by eufandem** [comment]
Looks awesome, great work!

**Comment by john-raymon** [comment]
Nice ⚡️The updated cart animation looks good!

**Comment by jaepass** [comment]
> Looks awesome, great work!

thanks for the sign off!

**Comment by jaepass** [comment]
> Nice ⚡️The updated cart animation looks good!

thanks for your help john!

**Pull request merged**
