### PR TITLE
Add Sold Out Indicator

### PR DESCRIPTION
**Pull request by PaitoAnderson**
New little feature to show that a product is sold out from the shop page listing and also product details.

Test Procedure:
1. Mark a product inventory as Managed with set Inventory available to 0.
2. Ensure Product Details page "Add to card" button says "Sold out" instead and is disabled for this product.
3. Ensure Product Details page related products shows a "SOLD OUT" banner on top of the product image when this product is displayed.
4. Ensure Shop page listing shows a "SOLD OUT" banner on top of the product image for this product.

### CODE REVIEW

**Comment by jaepass** [comment]
Great idea thank you, let me test this out real quick!

**Review by jaepass — COMMENTED** [review]
Looks great! Just one minor suggestion for the sold out button disabled styling -

Maybe something like this in the `.product-detail` class:
```
button {
  &:disabled {
    cursor: not-allowed;
    opacity: 60%;
  }
}
```

**Comment by PaitoAnderson** [comment]
Thanks for reviewing!

What do you think about doing this globally? I see the same issue with the "Make Payment" button in the checkout screen, so this would fix that too.

**Comment by PaitoAnderson** [comment]
Thanks @jaepass 🚀

**Pull request merged**
