### PR TITLE
Revert "fix checkout bug where pages/checkout.js redirects to homepage on successful checkout"

### PR DESCRIPTION
**Pull request by john-raymon**
Reverts chec/commercejs-nextjs-demo-store#90

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
...???

**Comment by john-raymon** [comment]
... ???

**Comment by john-raymon** [comment]
@ScopeyNZ I thought I needed a revert.

**Comment by ScopeyNZ** [comment]
Why?

**Comment by john-raymon** [comment]
@ScopeyNZ 

I merged my PR.

Got an email saying there's a vulnerability.

Assumed wrong that my pr was the issue.

So I revert the merge, then merged again when I realized my thinking was wrong.

Clearly rookie mistake on my end.

**Comment by ScopeyNZ** [comment]
Ok. Let's revert the revert, as we're pretty happy with this PR. We've got a separate process to deal with automated vulnerability alerts in node packages.

**Pull request merged**
